#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: claims-service
#          uri: http://localhost:8180
#          predicates:
#            - Path= /api/claims/**
#        - id: policy-service
#          uri: http://localhost:8089
#          predicates:
#            - Path= /api/policies/**
#        - id: user-service
#          uri: http://localhost:8080
#          predicates:
#            - Path= /api/users/**
#        - id: payment-service
#          uri: http://localhost:8084
#          predicates:
#            - Path= /api/payments/**
#        - id: notification-service
#          uri: http://localhost:8087
#          predicates:
#            - Path= /api/notifications/**
# 
# 
#server:
#  port: 8085
# 
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
# 
# 

spring:
  application:
    name: api-gateway

  cloud:
    gateway:

      # ======================
      # GLOBAL CORS CONFIG
      # ======================
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      # ======================
      # ROUTES CONFIGURATION
      # ======================
      routes:

        - id: claims-service
          uri: http://localhost:8180
          predicates:
            - Path=/api/claims/**

        - id: policy-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/policies/**

        - id: user-policy
          uri: http://localhost:8089
          predicates:
            - Path=/api/user-policies/**

        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/users/**

        - id: payment-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/payments/**

        - id: notification-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/notifications/**	
        - id: notification-service
          uri: http://localhost:8087
          predicates:
           - Path=/api/admin/notifications/**  	
        - id: customersupport-service
          uri: http://localhost:8090
          predicates:
           - Path=/api/support/**
        - id: customersupport-service
          uri: http://localhost:8090
          predicates:
           - Path=/api/admin/support/**

server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
