server:
  port: 8084
 
spring:
  application:
    name: PAYMENT-SERVICE
 
  datasource:
    url: jdbc:mysql://localhost:3306/paymentDB
    username: root
    password: Sahil@1402
 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
 
razorpay:
  key: rzp_test_SEQHT7tqw33nRK
  secret: jE5vrELN6ipS2aBYS2VPn52t
 