spring:
  application:
    name: customersupport-service

  datasource:
    url: jdbc:mysql://localhost:3306/customersupport_db?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Sahil@1402

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  h2:
    console:
      enabled: false

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            add:
              type:
                headers: false

server:
  port: 8090

services:
  policy:
    base-url: http://localhost:8089/api/policies
    connect-timeout-ms: 3000
    read-timeout-ms: 5000
#
#logging:
#  level:
#    root: INFO
#    org.springframework.web.client.RestTemplate: INFO
